"use client";

import { ArrowUpRight, Braces, Database, Download, ExternalLink, FileText, ShieldCheck, TerminalSquare, Wrench } from "lucide-react";
import { motion } from "framer-motion";
import { Navigation } from "@/components/Navigation";
import { TypographicPortrait } from "@/components/TypographicPortrait";
import { achievements, capabilities, experience, projects, skillGroups } from "@/data/portfolio";

const reveal = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0, transition: { duration: 0.55 } } };
const icons = [<ShieldCheck key="a" />, <Wrench key="b" />, <Braces key="c" />, <Database key="d" />];

export default function Home() {
  return <main id="top">
    <Navigation />
    <section className="hero page-section"><div className="hero-copy"><div className="eyebrow"><span className="marker" /> 01 / PROFESSIONAL PROFILE</div><p className="hero-name">ARIEL NAZARENO</p><h1>ERP<br /><em>TECHNICAL</em><br />SUPPORT<br /><span>SPECIALIST</span></h1><p className="hero-lede">I solve ERP problems, automate processes, and build practical technology solutions.</p><div className="hero-actions"><a className="button button-primary" href="#work">VIEW MY WORK <ArrowUpRight size={16} /></a><a className="button button-ghost" href="/resume.pdf" download>DOWNLOAD RESUME <Download size={16} /></a></div><div className="hero-meta"><span>SAP</span><span>ERP</span><span>AUTOMATION</span><span>DATA</span></div></div><div className="hero-art"><TypographicPortrait /><div className="portrait-caption"><span>THE TECHNOLOGY<br />BEHIND THE WORK</span><span>LOCAL / 001</span></div></div></section>
    <section className="signal-strip"><div><span className="live-dot" /> SYSTEM / PROFILE</div><div>SAP S/4HANA <b>ACTIVE</b></div><div>ERP SUPPORT <b>ACTIVE</b></div><div>AUTOMATION <b>ACTIVE</b></div><div>DATA <b>READY</b></div></section>
    <motion.section id="about" className="intro page-section" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.2 }} variants={reveal}><div className="section-label">02 / ABOUT</div><div className="intro-content"><h2>SYSTEMS.<br />PROBLEMS.<br /><span>SOLUTIONS.</span></h2><div><p className="large-copy">An ERP / SAP Technical Support Specialist focused on enterprise systems, technical support, automation, data, and practical solutions for business problems.</p><p className="muted">Where enterprise systems meet practical solutions. This portfolio is an evolving record of the tools, experiences, and thinking behind the work.</p></div></div></motion.section>
    <section className="capabilities page-section"><div className="section-label">03 / WHAT I DO</div><div className="capability-grid">{capabilities.map((item, index) => <motion.article key={item.index} initial="hidden" whileInView="show" viewport={{ once: true }} variants={{ ...reveal, show: { ...reveal.show, transition: { duration: 0.45, delay: index * 0.07 } } }}><div className="capability-top"><span>{item.index}</span>{icons[index]}</div><h3>{item.title}</h3><p>{item.text}</p></motion.article>)}</div></section>
    <section id="work" className="work page-section"><div className="section-heading"><div className="section-label">04 / SELECTED WORK</div><h2>CASE STUDIES<br /><span>IN PROGRESS.</span></h2><p>Practical systems work, represented with sanitized examples and verified outcomes only.</p></div><div className="project-list">{projects.map((project) => <article className="project" key={project.number}><div className="project-index">{project.number}</div><div className="project-main"><div className="project-category">{project.category}</div><h3>{project.title}</h3><p className="project-overview">{project.overview}</p><div className="project-details"><div><b>PROBLEM</b><p>{project.problem}</p></div><div><b>SOLUTION</b><p>{project.solution}</p></div><div><b>TECHNOLOGIES</b><p>{project.technologies}</p></div></div><div className="project-footer"><span>RESULT / {project.result}</span><span className="text-link">[ ADD GITHUB LINK ] <ExternalLink size={14} /></span></div></div></article>)}</div></section>
    <section id="experience" className="experience page-section"><div className="section-label">05 / EXPERIENCE</div><div className="timeline-heading"><h2>THE WORK<br /><span>SO FAR.</span></h2><p>Experience presented with the information currently verified. Mary Grace is the current role.</p></div><div className="timeline">{experience.map((item) => <article className={`timeline-item ${item.current ? "current" : ""} ${item.secondary ? "secondary" : ""}`} key={`${item.role}-${item.company}`}><div className="timeline-date">{item.date}</div><div className="timeline-line"><span /></div><div><div className="timeline-role">{item.role}</div><div className="timeline-company">{item.company}</div><p>{item.detail}</p></div></article>)}</div></section>
    <section className="skills page-section"><div className="section-label">06 / SKILLS</div><div className="skills-grid">{skillGroups.map(([title, ...skills]) => <div className="skill-group" key={title}><h3>{title}</h3><div>{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div>)}</div></section>
    <section className="achievements page-section"><div className="section-label">07 / ACHIEVEMENTS</div><div className="achievement-layout"><h2>PROOF OF<br /><span>PROGRESS.</span></h2><div className="achievement-list">{achievements.map((achievement, index) => <div key={achievement}><span>0{index + 1}</span><p>{achievement}</p></div>)}</div></div></section>
    <section id="resume" className="resume page-section"><div className="resume-panel"><div className="section-label">08 / RESUME</div><FileText size={28} strokeWidth={1.2} /><h2>THE FULL<br /><span>PICTURE.</span></h2><p>A concise record of experience, education, competencies, and certifications.</p><div className="resume-actions"><a className="button button-primary" href="/resume.pdf" target="_blank">VIEW FULL RESUME <ExternalLink size={16} /></a><a className="button button-ghost" href="/resume.pdf" download>DOWNLOAD PDF <Download size={16} /></a></div></div></section>
    <section id="contact" className="contact page-section"><div className="section-label">09 / CONTACT</div><div className="contact-content"><h2>LET&apos;S SOLVE<br /><span>A PROBLEM.</span></h2><p>For opportunities, collaboration, or a conversation about enterprise technology.</p><a className="contact-email" href="mailto:nazarenoariel02@gmail.com">nazarenoariel02@gmail.com <ArrowUpRight size={20} /></a><div className="contact-links"><a href="https://www.linkedin.com/in/ariel-nazareno/" target="_blank" rel="noreferrer">LINKEDIN <ArrowUpRight size={15} /></a><span>GITHUB / [ADD LINK]</span></div></div></section>
    <footer className="footer"><div><strong>ARIEL NAZARENO</strong><span>ERP / SAP TECHNICAL SUPPORT SPECIALIST</span></div><div className="footer-tags">SAP · ERP · AUTOMATION · DATA</div><div className="footer-bottom"><span>BUILT FROM SYSTEMS.</span><span><TerminalSquare size={14} /> SYSTEM READY_</span></div></footer>
  </main>;
}
