"use client";

import { ArrowUpRight, BarChart3, Braces, Database, Download, ExternalLink, FileText, Network, ShieldCheck, TerminalSquare, Wrench, X } from "lucide-react";
import { motion } from "framer-motion";
import Image from "next/image";
import { useState } from "react";
import { Navigation } from "@/components/Navigation";
import { TypographicPortrait } from "@/components/TypographicPortrait";
import { achievements, capabilities, experience, projects, skillGroups } from "@/data/portfolio";

const reveal = { hidden: { opacity: 0, y: 18 }, show: { opacity: 1, y: 0, transition: { duration: 0.55 } } };
const icons = [<ShieldCheck key="a" />, <Wrench key="b" />, <Braces key="c" />, <Database key="d" />];

export default function Home() {
  const [activeCaseStudy, setActiveCaseStudy] = useState<(typeof projects)[number] | null>(null);
  const projectVisuals = {
    mapper: <div className="project-visual mapper-visual" role="img" aria-label="SAP Master Data Mapper project visualization"><div className="mapper-root">MATERIAL</div><div className="mapper-branch branch-one"><b>PLANT 01</b><span>SLOC A</span><span>SLOC B</span><span>SLOC C</span></div><div className="mapper-branch branch-two"><b>PLANT 02</b><span>SLOC A</span><span>SLOC B</span></div><small className="visual-stamp">MAPPING / VALIDATE / GENERATE</small></div>,
    dashboard: <div className="project-visual dashboard-visual"><Image src="/dashboard.png" alt="ERP Task Monitoring Dashboard preview showing ticket status, workload, departments, priorities, and SLA reporting" width={1904} height={880} style={{ width: "100%", height: "auto", display: "block" }} /></div>,
    materials: <div className="project-visual materials-visual" role="img" aria-label="SAP Material Master Data Tools project visualization"><div className="process-node">SAP MATERIAL</div><div className="process-flow"><span>EXTRACT</span><i /><span>VALIDATE</span><i /><span>CLEAN</span><i /><span>TRANSFORM</span><i /><span>MIGRATE</span></div><small className="visual-stamp">UOM / PLANT / SLOC / VALUATION</small></div>,
    itsm: <div className="project-visual itsm-visual" role="img" aria-label="Mary Grace ITSM project visualization"><div className="ticket-shell"><small>TICKET LIFECYCLE / 001</small><div className="ticket-flow"><span>NEW</span><i /><span>ASSIGNED</span><i /><span>IN PROGRESS</span><i /><span>RESOLVED</span></div><div className="ticket-meta"><b>SLA</b><b>PRIORITY</b><b>ASSIGNEE</b><b>STATUS</b></div></div></div>,
  };
  return <main id="top">
    <Navigation />
    <section className="hero page-section"><div className="hero-copy"><div className="eyebrow"><span className="marker" /> 01 / PROFESSIONAL PROFILE</div><p className="hero-name">ARIEL NAZARENO</p><h1>ERP<br /><em>TECHNICAL</em><br />SUPPORT<br /><span>SPECIALIST</span></h1><p className="hero-lede">I solve ERP problems, automate processes, and build practical technology solutions.</p><div className="hero-actions"><a className="button button-primary" href="#work">VIEW MY WORK <ArrowUpRight size={16} /></a><a className="button button-ghost" href="/resume.pdf" download>DOWNLOAD RESUME <Download size={16} /></a></div><div className="hero-meta"><span>SAP</span><span>ERP</span><span>AUTOMATION</span><span>DATA</span></div></div><div className="hero-art"><TypographicPortrait /><div className="portrait-caption"><span>THE TECHNOLOGY<br />BEHIND THE WORK</span><span>LOCAL / 001</span></div></div></section>
    <section className="signal-strip"><div><span className="live-dot" /> SYSTEM / PROFILE</div><div>SAP S/4HANA <b>ACTIVE</b></div><div>ERP SUPPORT <b>ACTIVE</b></div><div>AUTOMATION <b>ACTIVE</b></div><div>DATA <b>READY</b></div></section>
    <motion.section id="about" className="intro page-section" initial="hidden" whileInView="show" viewport={{ once: true, amount: 0.2 }} variants={reveal}><div className="section-label">02 / ABOUT</div><div className="intro-content"><h2>SYSTEMS.<br />PROBLEMS.<br /><span>SOLUTIONS.</span></h2><div><p className="large-copy">An ERP / SAP Technical Support Specialist focused on enterprise systems, technical support, automation, data, and practical solutions for business problems.</p><p className="muted">Where enterprise systems meet practical solutions. This portfolio is an evolving record of the tools, experiences, and thinking behind the work.</p></div></div></motion.section>
    <section className="capabilities page-section"><div className="section-label">03 / WHAT I DO</div><div className="capability-grid">{capabilities.map((item, index) => <motion.article key={item.index} initial="hidden" whileInView="show" viewport={{ once: true }} variants={{ ...reveal, show: { ...reveal.show, transition: { duration: 0.45, delay: index * 0.07 } } }}><div className="capability-top"><span>{item.index}</span>{icons[index]}</div><h3>{item.title}</h3><p>{item.text}</p></motion.article>)}</div></section>
    <section id="work" className="work page-section"><div className="section-heading"><div className="section-label"><Network size={14} /> 04 / SELECTED WORK</div><h2>CASE STUDIES<br /><span>IN PROGRESS.</span></h2><p>Practical systems work, represented with sanitized examples and verified outcomes only.</p></div><div className="project-list">{projects.map((project) => <article className="project" key={project.number}><div className="project-index">{project.number}</div><div className="project-main"><div className="project-visual-frame">{projectVisuals[project.visual as keyof typeof projectVisuals]}</div><div className="project-category">{project.category}</div><div className="project-title-row"><h3>{project.title}</h3><span className="project-status">{project.status}</span></div><p className="project-overview">{project.overview}</p><div className="project-tech">{project.technologies.map((technology) => <span key={technology}>{technology}</span>)}</div><div className="project-footer"><span className="project-action">{project.href ? <a className="text-link" href={project.href} target="_blank" rel="noopener noreferrer">View on GitHub <ExternalLink size={14} /></a> : <button className="text-link case-study-button" onClick={() => setActiveCaseStudy(project)}>View Case Study <BarChart3 size={14} /></button>}</span><span className="project-kind">{project.href ? "PUBLIC REPOSITORY" : "SANITIZED PREVIEW"}</span></div></div></article>)}</div></section>
    {activeCaseStudy?.caseStudy && <div className="case-study-backdrop" role="presentation" onClick={() => setActiveCaseStudy(null)}><article className="case-study-modal" role="dialog" aria-modal="true" aria-labelledby="case-study-title" onClick={(event) => event.stopPropagation()}><button className="case-study-close" onClick={() => setActiveCaseStudy(null)} aria-label="Close case study"><X size={18} /></button><div className="section-label">INTERNAL PROJECT</div><h2 id="case-study-title">{activeCaseStudy.title}</h2><div className="case-study-preview">{projectVisuals.dashboard}</div><div className="case-study-copy"><div><b>PROBLEM</b><p>{activeCaseStudy.caseStudy.problem}</p></div><div><b>SOLUTION</b><p>{activeCaseStudy.caseStudy.solution}</p></div><div><b>KEY DASHBOARD CAPABILITIES</b><ul>{activeCaseStudy.caseStudy.features.map((feature) => <li key={feature}>{feature}</li>)}</ul></div></div></article></div>}
    <section id="experience" className="experience page-section"><div className="section-label">05 / EXPERIENCE</div><div className="timeline-heading"><h2>THE WORK<br /><span>SO FAR.</span></h2><p>Experience presented with the information currently verified. Mary Grace is the current role.</p></div><div className="timeline">{experience.map((item) => <article className={`timeline-item ${item.current ? "current" : ""} ${item.secondary ? "secondary" : ""}`} key={`${item.role}-${item.company}`}><div className="timeline-date">{item.date}</div><div className="timeline-line"><span /></div><div><div className="timeline-role">{item.role}</div><div className="timeline-company">{item.company}</div><p>{item.detail}</p></div></article>)}</div></section>
    <section className="skills page-section"><div className="section-label">06 / SKILLS</div><div className="skills-grid">{skillGroups.map(([title, ...skills]) => <div className="skill-group" key={title}><h3>{title}</h3><div>{skills.map((skill) => <span key={skill}>{skill}</span>)}</div></div>)}</div></section>
    <section className="achievements page-section"><div className="section-label">07 / ACHIEVEMENTS</div><div className="achievement-layout"><h2>PROOF OF<br /><span>PROGRESS.</span></h2><div className="achievement-list">{achievements.map((achievement, index) => <div key={achievement}><span>0{index + 1}</span><p>{achievement}</p></div>)}</div></div></section>
    <section id="resume" className="resume page-section"><div className="resume-panel"><div className="section-label">08 / RESUME</div><FileText size={28} strokeWidth={1.2} /><h2>THE FULL<br /><span>PICTURE.</span></h2><p>A concise record of experience, education, competencies, and certifications.</p><div className="resume-actions"><a className="button button-primary" href="/resume.pdf" target="_blank">VIEW FULL RESUME <ExternalLink size={16} /></a><a className="button button-ghost" href="/resume.pdf" download>DOWNLOAD PDF <Download size={16} /></a></div></div></section>
    <section id="contact" className="contact page-section"><div className="section-label">09 / CONTACT</div><div className="contact-content"><h2>LET&apos;S SOLVE<br /><span>A PROBLEM.</span></h2><p>For opportunities, collaboration, or a conversation about enterprise technology.</p><a className="contact-email" href="mailto:nazarenoariel02@gmail.com">nazarenoariel02@gmail.com <ArrowUpRight size={20} /></a><div className="contact-links"><a href="https://www.linkedin.com/in/ariel-nazareno/" target="_blank" rel="noreferrer">LINKEDIN <ArrowUpRight size={15} /></a><span>GITHUB / [ADD LINK]</span></div></div></section>
    <footer className="footer"><div><strong>ARIEL NAZARENO</strong><span>ERP / SAP TECHNICAL SUPPORT SPECIALIST</span></div><div className="footer-tags">SAP · ERP · AUTOMATION · DATA</div><div className="footer-bottom"><span>BUILT FROM SYSTEMS.</span><span><TerminalSquare size={14} /> SYSTEM READY_</span></div></footer>
  </main>;
}
